In [2]:
import os
import tensorflow as tf

Init Plugin
Init Graph Optimizer
Init Kernel


In [21]:
x= tf.constant(4, shape=(1,1),dtype=tf.float32)#single scaler
print(x)

y=tf.constant([[1,2,3],[4,5,6]])
print(y)

z=tf.ones(3,3)
print(z)

w=tf.zeros(3,3)
print(w)

#eye
p=tf.eye(3)
print(p)

#random value for normal distribution
ws=tf.random.normal((3,3),mean=0,stddev=1)
print(ws)


#random value for uniform distribution
wz=tf.random.uniform((3,3),minval=0,maxval=1)
print(wz)

#range function
wy=tf.range(10)
print(wy)

#cast because imutable
wx=tf.cast(wy, dtype=tf.float32)
print(wx)


tf.Tensor([[4.]], shape=(1, 1), dtype=float32)
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
tf.Tensor([1 1 1], shape=(3,), dtype=int32)
tf.Tensor([0 0 0], shape=(3,), dtype=int32)
tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[ 2.0907657  -0.5931975   0.11283968]
 [ 0.31116456 -0.4336749  -0.07594799]
 [-0.01198864  0.45448732 -0.07282386]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[0.66691935 0.2924024  0.7701242 ]
 [0.917176   0.25480163 0.606426  ]
 [0.85407686 0.4991871  0.48812103]], shape=(3, 3), dtype=float32)
tf.Tensor([0 1 2 3 4 5 6 7 8 9], shape=(10,), dtype=int32)
tf.Tensor([0 1 2 3 4 5 6 7 8 9], shape=(10,), dtype=int32)
tf.Tensor([0. 1. 2. 3. 4. 5. 6. 7. 8. 9.], shape=(10,), dtype=float32)


In [37]:
#tensor operations by elementwise
x= tf.constant([1,2,3])
y= tf.constant([4,5,6])
#z=tf.add(x,y) #addition
#z=x+y
# z=tf.subtract(x,y) #subtraction
# z=x-y
#z=tf.multiply(x,y) #multiplication
#z=x*y

#z=tf.divide(x,y) #divition
#z=x/y

#z=tf.tensordot(x,y,axes=1) #multiplication and summition
z=x**3 # exponential po# wer
print(z)

tf.Tensor([ 1  8 27], shape=(3,), dtype=int32)


In [42]:
# elements wise matrix multiplication
x=tf.random.normal((2,2))
y=tf.random.normal((2,2))
#z=tf.matmul(x,y)#matrix multiplication; must be same column of x and row shape of y
z=x@y
print(z)

tf.Tensor(
[[-1.824566   -3.500403  ]
 [-0.71994746 -1.8026938 ]], shape=(2, 2), dtype=float32)


In [51]:
#slicing, indexing
x= tf.constant([[1,2,3,4],[5,6,7,8]])
print(x)
print(x[0])#slicing first row
print(x[:,0])#slicing all row and first column
print(x[1,:])#slicing first row and all column
print(x[0,1:3])#slicing first row and 2nd, 3rd column
print(x[0,1])#slicing fixed element

tf.Tensor(
[[1 2 3 4]
 [5 6 7 8]], shape=(2, 4), dtype=int32)
tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)
tf.Tensor([1 5], shape=(2,), dtype=int32)
tf.Tensor([5 6 7 8], shape=(4,), dtype=int32)
tf.Tensor([2 3], shape=(2,), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)


In [55]:
# reshaping
x=tf.random.uniform((2,3))
print(x)

x=tf.reshape(x, (3,2))#convert 3 rows and 2 columns
print(x)

x=tf.reshape(x, (6))#convert single rows
print(x)

x=tf.reshape(x, (-1,2))#convert 3 rows and 2 columns again
print(x)

tf.Tensor(
[[0.66691935 0.2924024  0.7701242 ]
 [0.917176   0.25480163 0.606426  ]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[0.66691935 0.2924024 ]
 [0.7701242  0.917176  ]
 [0.25480163 0.606426  ]], shape=(3, 2), dtype=float32)
tf.Tensor([0.66691935 0.2924024  0.7701242  0.917176   0.25480163 0.606426  ], shape=(6,), dtype=float32)
tf.Tensor(
[[0.66691935 0.2924024 ]
 [0.7701242  0.917176  ]
 [0.25480163 0.606426  ]], shape=(3, 2), dtype=float32)


In [59]:
# convert numpy array
x=tf.random.uniform((2,3))
print(x)

x=x.numpy() #convert tensor to numpy
print(x)
print(type(x))

x=tf.convert_to_tensor(x) #convert numpy to tensor
print(x)
print(type(x))

tf.Tensor(
[[0.5268742  0.34426558 0.41501665]
 [0.105389   0.9367095  0.92568815]], shape=(2, 3), dtype=float32)
[[0.5268742  0.34426558 0.41501665]
 [0.105389   0.9367095  0.92568815]]
<class 'numpy.ndarray'>
tf.Tensor(
[[0.5268742  0.34426558 0.41501665]
 [0.105389   0.9367095  0.92568815]], shape=(2, 3), dtype=float32)
<class 'tensorflow.python.framework.ops.EagerTensor'>


In [62]:
# string tensor
x=tf.constant('sanowar')
print(x)

x=tf.constant(['sanowar','anowar','billah'])
print(x)

tf.Tensor(b'sanowar', shape=(), dtype=string)
tf.Tensor([b'sanowar' b'anowar' b'billah'], shape=(3,), dtype=string)


In [63]:
# variabl
x=tf.constant([1,2,3])
print(x)

x=tf.Variable([1,2,3])#variable tensorflow, modify the tensor
print(x)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)
<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([1, 2, 3], dtype=int32)>
